### ISSUE TITLE
Generate columns independently from defined columns

### ISSUE THREAD

**Issue by szalonna** [predixdesignsystem/px-data-table#68] opened 2016-10-28 09:24 UTC
# Expected behavior

When I define custom columns, only those defined columns are visible with the given label
# Actual behavior

The table generates columns for all the keys in the object. It does not depends on if I added custom column for the given key or not, it creates a new generic column with the key as label. If I interact with the generated columns and there is a custom column for that key, the custom column highlights as well (for example if I order by column)
# Environment

It happens in multiple browser and operating systems
# Code example

https://jsfiddle.net/szalonna/pp4dmuqj/5/
# Possible duplicates
#28  Multiple Columns insplite of px-data-table-column

**Comment by szalonna** [comment] 2016-11-01 18:45
Heelo Team,

Can you confirm the issue? What do you estimate, when will it get fixed?

Thanks!

**Comment by mdwragg** [comment] 2016-11-01 18:52
I'm only back from vacation today. Wow, thats a lot of code! I'll have to figure out what is happening...

**Comment by szalonna** [comment] 2016-11-02 08:36
The HTML part contains the Polymer and other dependencies for px-data-table, Angular 2 and other dependencies and the huge inline code is the angular2-polymer component, but I was not able to find a proper CDN which hosts it in Javascript code, not in Typescript.
What really matters is in the Javascript part. We have a hardcoded dataset and we want to assign it as a data source to the px-data-table with custom headers, but as you can see, there are other, autogenerated columns for all the data keys.

**Comment by szalonna** [comment] 2016-11-07 09:57
Hello Team,
Is there any update related to this? Is there any workaround until it get fixed?
Thanks!

**Comment by szalonna** [comment] 2016-12-13 15:41
Hello Team,
Is there any news?
Thanks!

**Comment by mdwragg** [comment] 2016-12-13 18:05
Hi @szalonna, sorry, pressures our current release have kept me away from this... The codepen no longer works sadly, would it be possible to put this in a repo so I can locally debug?

Appreciate your efforts to help us recreate this.
Thanks!

**Comment by szalonna** [comment] 2016-12-23 09:11
Hello @mdwragg 

I updated the Jsfiddle demo, it works fine for me right now.
https://jsfiddle.net/pp4dmuqj/6/
The important part is that in the Angular component template I define only two columns to display but is generates columns for the other datakeys as well.

Thanks!

**Comment by randyaskin** [comment] 2017-03-15 23:36
I may have misunderstood this issue based on the title... looks like my changes in 2.0.0 may not fix this Angular issue? Feel free to test/comment.

**Comment by waseem18** [comment] 2017-04-14 19:30
Looks like the issue hasn't yet been resolved! Using version 2.1.3, but still getting multiple columns in spite of `px-data-table-column`. Issue #28 to be precise.

**Comment by czambran** [comment] 2017-05-10 21:34
@randyaskin The bug is still present in version 2.1.5. I tracked down the issue to the observer function _dataChanged being called right after the attached lifecycle event fired but before _columnChanged. 

I wasn't able to reproduce this using a Polymer router because the Angular Router destroys the component on route change while the Polymer one doesn't so the series of events always fire in the right order when using the polymer router 

You can use the following app to reproduce the issue: https://github.com/czambran/pxDataTableIssueInAngularApp

Steps to see the issue(Assuming you are running it under http://localhost:4200/) :
1. Go to http://localhost:4200/table . You should only see the specified columns. If you reload the page the correct columns will show
2. Go to http://localhost:4200/ and click on the table link at the top of the page. You should see duplicate columns

I will issue a PR in a bit with a possible fix

**Comment by colinjlacy** [comment] 2018-02-15 17:01
As it were, I'm seeing this in px-data-table 5.1.12, in Angular 4.4.6, Chrome 64.0.3282.140:
<img width="1364" alt="screen shot 2018-02-15 at 10 59 02 am" src="https://user-images.githubusercontent.com/4993605/36269640-4186a84a-123f-11e8-8c83-ab6b6cdaecb2.png">
```
<p>
    Hi Randy!
</p>
<p>
    {{tableDataString}}
</p>
<px-data-table [tableData]="tableData">
    <px-data-table-column
            name="title"
            type="html">
    </px-data-table-column>
    <px-data-table-column
            name="active"
            type="html">
    </px-data-table-column>
    <px-data-table-column
            name="actions"
            type="html">
    </px-data-table-column>
</px-data-table>
```

**Comment by mdwragg** [comment] 2018-05-07 22:10
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid

**Closed by mdwragg** 2018-05-07 22:10 UTC
