### ISSUE TITLE
Checkbox, Number Editor and Conditional Editing support

### ISSUE THREAD

**Issue by a3986** [predixdesignsystem/px-data-table#105] opened 2017-03-03 10:16 UTC
# New Requirements
Hi,

I have some enhancements required for my current project which are currently not supported by current px-data-table. The requirements are as follows
1) Support for new cell editors (Checkbox and Number Editor). Select/Deselect all functionality on checkbox column
2) Conditional editing of a particular column.Details in the image below
3) Number editor - support for min,max,stepsize properties
4) Hide filter-row even when some columns are filterable. Use case - I have to provide filter functionality from outside the grid. There is a search box in top section of grid. 

# Screenshot - Details

![image](https://cloud.githubusercontent.com/assets/625481/23546163/57826f40-0024-11e7-90e8-1e1a0bfeed50.png)

 # Changes
I have made the code changes and are available in https://github.com/a3986/px-data-table

# Demo
I have made changes in demo.html to display all the above mentioned functionalities.

# Test Cases
All the current test cases are working fine. The test cases for the above mentioned changes are in progress

# Known Issues/Workaround
With checkbox and number editor, when page changes (data assigned to grid changes) but the editors used are still the same (checkbox and number editors still show the value from page 1). 
To fix this, as a workaround, forceRender function is implemented which gets executed whenever a page is changed or sorting and filtering is applied.

# Requirement, Design and Code Review
Please review the requirement, design and code and please let me know if I can raise a pull request for the same once the test cases are completed. Also, let me know in case I need to make any changes before I can make this pull request.

**Comment by randyaskin** [comment] 2017-03-10 00:03
I talked this over briefly with our TPM Aileen Hackett. We found the boolean column type to be potentially confusing with the existing Selected column full of checkboxes. Not sure what the use case is, but you could achieve the same with a dropdown with yes/no or true/false options. The number editor does seem useful, and we've also heard requests for date columns with proper sorting / selection of dates.

**Comment by a3986** [comment] 2017-03-10 02:03
The use case for Boolean column is when user wants to edit some Boolean data and when not using it for selecting multiple rows.
In my case, there are multiple Boolean fields for enabling or disabling some other fields in a row.
Yes. The use case can be achieved using drop-down with true/false but the problem with dropdown is that everytime it requires two clicks from user to change a particular value. Also, in case of Boolean column, user gets an option to 'Check/Uncheck All' values in a single click. So adding a Boolean column can be user friendly and will help user to quickly make some changes as compared to when using drop-down

Below is a screenshot of sample use case where one may require multiple Boolean fields and a 'Check/uncheck All' option

![qk95k](https://cloud.githubusercontent.com/assets/625481/23778805/84616960-0562-11e7-98b4-c42905849ec1.png)

Note: This is just a sample use case.

**Comment by a3986** [comment] 2017-03-15 14:06
I have some more requirements in my current project. So I have updated the code base at https://github.com/a3986/px-data-table with required features

Features details 
1. Row Level Validation support - Whenever a value changes in a cell, it triggers validation for other cells in the same row
2. Cell Renderer - If a value needs to be transformed/formatted and then shown to end user, then cell renderers can be used. This feature is inline with the enhancement request raised at https://github.com/PredixDev/px-data-table/issues/92

![cellrendererandrowlevelvalidation](https://cloud.githubusercontent.com/assets/625481/23951702/fd449a9a-09b4-11e7-817b-5f3f58e5e909.png)

Please consider these two requirements too for the pull request.

**Comment by kornfein** [comment] 2017-04-19 15:24
We have the same requirement for the checkbox which seems to be called boolean here.  I also agree it is not the same as the row selection.   Note that I was able to insert a checkbox into the data table using the html type. But the table data did not contain the value, so I couldn't tell if the checkboxes were checked programtically.

**Comment by a3986** [comment] 2017-04-20 14:01
@randyaskin Any updates/comments?

@kornfein The boolean/checkbox column feature required by you is implemented at  https://github.com/a3986/px-data-table . You can check if it satisfies your requirement.

**Comment by kornfein** [comment] 2017-04-20 17:36
**The boolean capability that is part of this branch does exactly what we need**.  Will this get merged into the master px-data-table?   I've not used a branch before on a Predix component and just want to understand how this will be maintained, For example i suspect if i do a bower update it would overwrite this code?

**Comment by randyaskin** [comment] 2017-04-20 18:08
@a3986 Can you please submit a pull request from your forked repo to our master? That is the first step. Then we will need to review the code, demo, unit tests, etc and merge the PR if everything is ok. Part of the problem is that our team has a lot on its plate right now doing a major redesign of all of the components in Px, which not only consumes most of our bandwidth but also complicates our branching and versioning strategy until June when we're ready to release the whole redesign. We'll see what we can do.

**Comment by mdwragg** [comment] 2018-05-07 22:11
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid

**Closed by mdwragg** 2018-05-07 22:11 UTC
Labels: enhancement
