### ISSUE TITLE
px-data-table show/hide column chooser dropdown needs to set programatically on load of px-data-table compleates

### ISSUE THREAD

**Issue by shashidharBM** [predixdesignsystem/px-data-table#176] opened 2017-11-13 12:33 UTC
Hi Team,

I have scenario, where user can store his preferences based on the show/hide dropdown component

## Code examples 
         this.async(() => {
                const hiddenCols = this.hiddenColumns; // hiddenColumns array is coming from the service to check which columns need to hide
const newObj = [];
                const tableCols = document.querySelector('#summaryDataTable aha-table')._columnChooserItems;
                for (let k = 0; k < hiddenCols.length; k++) {
                    for (let l = 0; l < tableCols.length; l++) {
                      if (hiddenCols[k] === tableCols[l].val) {
                        tableCols[l].selected = false;
                      }
                      newObj.push(tableCols[l]);
                    }
                  }
 document.querySelector('#summaryDataTable aha-table')._columnChooserItems = newObj;
                },2000);

## Another approach with hideColumn() , method of aha-table
    this.async(() => {
                const hiddenCols = this.hiddenColumns;
                const tableCols = document.querySelector('#summaryDataTable aha-table')._columnChooserItems;
                for (let k = 0; k < hiddenCols.length; k++) {
                    for (let l = 0; l < tableCols.length; l++) {
                      if (hiddenCols[k] === tableCols[l].val) {
                        tableCols.hideColumn(hiddenCols[k].key);
                      }
                    }
                  }
                },2000);

**Comment by mdwragg** [comment] 2017-11-13 15:46
Hi, thanks for your issue. Sadly I’m non-the-wiser about what the issue is though.

Are you requesting a new API to set hidden columns? Do you need more events out of the data table?

Pull requests always welcome, of course, if it is easier to explain in code...

**Comment by mdwragg** [comment] 2018-05-07 22:15
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid

**Closed by mdwragg** 2018-05-07 22:15 UTC
